const API_KEY = 'ipb_live_9N1HEHqCnBWxsPNwyz85yhjOoscJTpVO8r6rKzbK';
const OFFICE_LOCATION_LATITUDE = 42.659360;
const OFFICE_LOCATION_LONGITUDE = 23.379953;

module.exports = {
    API_KEY,
    OFFICE_LOCATION_LATITUDE,
    OFFICE_LOCATION_LONGITUDE
};
